// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace jdrBack.Models
{
    public partial class Fight
    {
        public int FightId { get; set; }
        public string Opponent { get; set; }
        public string Strength { get; set; }
        public string Stamina { get; set; }
        public int? Flee { get; set; }
        public string DeathText { get; set; }
        public string VictoryText { get; set; }
    }
}