// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace jdrBack.Models
{
    public partial class Scene
    {
        public int SceneId { get; set; }
        public string Description { get; set; }
        public string Decor { get; set; }
    }
}